version: '2'
services:
  emotionfeedback-app:
    image: emotionfeedback
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://emotionfeedback-postgresql:5432/emotionFeedback
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8089:8089
  emotionfeedback-postgresql:
    extends:
      file: postgresql.yml
      service: emotionfeedback-postgresql
